import type { ConsolidationModelOutput } from "@/lib/codex/types";

function normalizeGeneratedAt(generatedAt?: string) {
  return generatedAt && generatedAt.trim().length > 0 ? generatedAt : new Date().toISOString();
}

function renderListOrNone(lines: string[]) {
  return lines.length > 0 ? lines.join("\n") : "None";
}

function sanitizeInline(value: string) {
  return value.replace(/\r?\n/g, " ").trim();
}

export function renderPackToMarkdown(
  pack: ConsolidationModelOutput,
  repoFullName: string,
  generatedAt?: string,
): string {
  const generatedTimestamp = normalizeGeneratedAt(generatedAt);

  const promotedRules = renderListOrNone(
    pack.rules_to_promote.map((rule) => {
      const triggers = rule.triggers.length > 0 ? rule.triggers.map(sanitizeInline).join(", ") : "None";

      return [
        `### ${sanitizeInline(rule.title)}`,
        sanitizeInline(rule.description),
        `**Triggers:** ${triggers}`,
        `**Source episodes:** ${rule.source_episode_ids.length}`,
        `**Rule key:** ${rule.rule_key}`,
      ].join("\n");
    }),
  );

  const contradictions = renderListOrNone(
    pack.contradictions.map((contradiction) => {
      const reason = sanitizeInline(contradiction.reason);
      return [`- ! ${reason}`, `  Episodes: ${contradiction.left_episode_id} <-> ${contradiction.right_episode_id}`].join(
        "\n",
      );
    }),
  );

  const salienceUpdates = renderListOrNone(
    pack.salience_updates.map(
      (update) =>
        `- ${update.episode_id} -> ${update.salience_score} (${sanitizeInline(update.reason)})`,
    ),
  );

  const pruningCandidates = renderListOrNone(pack.prune_candidates.map((id) => `- ${id}`));

  const footer = `_Generated by [Hippocampus](https://github.com/) | ${pack.rules_to_promote.length} rules | ${pack.contradictions.length} contradictions_`;

  return [
    `# Team Memory Pack - ${sanitizeInline(repoFullName)}`,
    `> Auto-generated by Hippocampus on ${generatedTimestamp}. Review before merging.`,
    "",
    "## Promoted Rules",
    promotedRules,
    "",
    "## Contradictions",
    contradictions,
    "",
    "## Salience Updates",
    salienceUpdates,
    "",
    "## Pruning Candidates",
    pruningCandidates,
    "",
    "---",
    footer,
    "",
  ].join("\n");
}
