import { beforeEach, describe, expect, it, vi } from "vitest";

const requestMock = vi.hoisted(() => vi.fn());

vi.mock("octokit", () => {
  class Octokit {
    request = requestMock;

    constructor() {}
  }

  return {
    Octokit,
  };
});

import { createPackPR, type CreatePackPRInput, type CreatePackPRResult } from "@/lib/distribution/create-pack-pr";

function mockRequestSequenceForCreate() {
  vi.mocked(requestMock)
    .mockResolvedValueOnce({ data: { object: { sha: "base-sha" } } })
    .mockResolvedValueOnce({ data: {} })
    .mockRejectedValueOnce({ status: 404, message: "Not Found" })
    .mockResolvedValueOnce({ data: { commit: { sha: "commit-sha" } } })
    .mockResolvedValueOnce({ data: { number: 42, html_url: "https://github.com/acme/demo/pull/42" } });
}

function findRequestCall(method: string) {
  return vi.mocked(requestMock).mock.calls.find((call: unknown[]) => call[0] === method);
}

describe("createPackPR", () => {
  beforeEach(() => {
    vi.mocked(requestMock).mockReset();
  });

  it("creates branch, commits markdown, and opens PR with defaults", async () => {
    mockRequestSequenceForCreate();

    const input: CreatePackPRInput = {
      token: "ghs_123",
      owner: "acme",
      repo: "demo",
      defaultBranch: "main",
      markdownContent: "# Team Memory Pack - acme/demo\n\n### Retry rules",
    };

    const result = await createPackPR(input);

    const typedResult: CreatePackPRResult = result;

    expect(typedResult.prNumber).toBe(42);
    expect(typedResult.prUrl).toBe("https://github.com/acme/demo/pull/42");
    expect(typedResult.sha).toBe("commit-sha");
    expect(typedResult.branch).toMatch(/^hippocampus\/team-memory-\d+$/);

    expect(vi.mocked(requestMock)).toHaveBeenCalledWith("GET /repos/{owner}/{repo}/git/ref/heads/{ref}", {
      owner: "acme",
      repo: "demo",
      ref: "main",
    });

    const putCall = findRequestCall("PUT /repos/{owner}/{repo}/contents/{path}");
    expect(putCall?.[1]).toMatchObject({
      owner: "acme",
      repo: "demo",
      path: ".codex/team-memory.md",
      message: "chore(hippocampus): update team memory pack",
    });

    const pullCall = findRequestCall("POST /repos/{owner}/{repo}/pulls");
    expect(pullCall?.[1]).toMatchObject({
      owner: "acme",
      repo: "demo",
      title: "[Hippocampus] Update team memory pack",
      base: "main",
    });
    expect(String((pullCall?.[1] as { body?: unknown })?.body ?? "")).toContain("Generated by Hippocampus.");
  });

  it("uses existing file sha when updating existing markdown", async () => {
    vi.mocked(requestMock)
      .mockResolvedValueOnce({ data: { object: { sha: "base-sha" } } })
      .mockResolvedValueOnce({ data: {} })
      .mockResolvedValueOnce({ data: { sha: "existing-file-sha" } })
      .mockResolvedValueOnce({ data: { commit: { sha: "commit-sha" } } })
      .mockResolvedValueOnce({ data: { number: 7, html_url: "https://github.com/acme/demo/pull/7" } });

    await createPackPR({
      token: "ghs_456",
      owner: "acme",
      repo: "demo",
      defaultBranch: "main",
      markdownContent: "content",
      commitMessage: "custom commit",
      prTitle: "custom title",
      prBody: "custom body",
    });

    const putCall = findRequestCall("PUT /repos/{owner}/{repo}/contents/{path}");
    expect(putCall?.[1]).toMatchObject({
      sha: "existing-file-sha",
      message: "custom commit",
      branch: expect.stringMatching(/^hippocampus\/team-memory-\d+$/),
    });

    const pullCall = findRequestCall("POST /repos/{owner}/{repo}/pulls");
    expect(pullCall?.[1]).toMatchObject({
      title: "custom title",
      body: "custom body",
    });
  });
});
